# Generated by Django 4.1.6 on 2023-05-13 17:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('fullstackcapapi', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='userlike',
            name='user',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='fullstackcapapi.user'),
        ),
    ]
