# Generated by Django 4.1.6 on 2023-05-13 17:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('fullstackcapapi', '0002_userlike_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userlike',
            name='user',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='fullstackcapapi.user'),
        ),
    ]
